### ISSUE TITLE
Potential Typo in sylph-tax Merge Command

### ISSUE THREAD

**Issue by tianci-zhao** [bluenote-1577/sylph-tax#1]
Hi @bluenote-1577,

I noticed that in the merge multiple results command below, --columns might be a small typo—it worked successfully for me with --column. I also double-checked the subcommand to confirm.

#merge multiple results
sylph-tax merge *.sylphmpa --columns relative_abundance -o merged_abundance_file.tsv

Just flag this in case it helps. Please feel free to ignore if it’s not an issue!

Thanks again for this amazing tool.

Cheers,
Tianci

**Comment by bluenote-1577** [comment]
Hi @tianci-zhao, thanks for catching this bug. Much appreciated. Changed now.
